service: Layers

package:
  individually: true

custom:
  serviceName: layers

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    TZ: Asia/Tokyo

layers:
  poppler:
    path: poppler
    description: pdf2imageなどに必要なpopplerのインストール
    compatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8
